//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patientTbl()
        {
            this.visitTbls = new HashSet<visitTbl>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public Nullable<int> doctorId { get; set; }
        public string VisitorHis { get; set; }
        public string discharged { get; set; }
        public string password { get; set; }
    
        public virtual doctorTbl doctorTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitTbl> visitTbls { get; set; }
    }
}
